export const FETCH_ADD_COMMENT = 'FETCH_ADD_COMMENT'
export const FETCH_ADD_COMMENT_DONE = 'FETCH_ADD_COMMENT_DONE'
export const FETCH_ADD_COMMENT_ERROR = 'FETCH_ADD_COMMENT_ERROR'

export const FETCH_UPDATE_COMMENT = 'FETCH_UPDATE_COMMENT'
export const FETCH_UPDATE_COMMENT_DONE = 'FETCH_UPDATE_COMMENT_DONE'
export const FETCH_UPDATE_COMMENT_ERROR = 'FETCH_UPDATE_COMMENT_ERROR'

export const FETCH_REMOVE_COMMENT = 'FETCH_REMOVE_COMMENT'
export const FETCH_REMOVE_COMMENT_DONE = 'FETCH_REMOVE_COMMENT_DONE'
export const FETCH_REMOVE_COMMENT_ERROR = 'FETCH_REMOVE_COMMENT_ERROR'

export const FETCH_ALL_COMMENTS = 'FETCH_ALL_COMMENTS'
export const FETCH_ALL_COMMENTS_DONE = 'FETCH_ALL_COMMENTS_DONE'
export const FETCH_ALL_COMMENTS_ERROR = 'FETCH_ALL_COMMENTS_ERROR'

export const TOGGLE_EDIT_COMMENT = 'TOGGLE_EDIT_COMMENT'
