export const FETCH_ADD_POST = 'FETCH_ADD_POST'
export const FETCH_ADD_POST_DONE = 'FETCH_ADD_POST_DONE'
export const FETCH_ADD_POST_ERROR = 'FETCH_ADD_POST_ERROR'

export const FETCH_UPDATED_POST = 'FETCH_UPDATED_POST'
export const FETCH_UPDATED_POST_DONE = 'FETCH_UPDATED_POST_DONE'
export const FETCH_UPDATED_POST_ERROR = 'FETCH_UPDATED_POST_ERROR'

export const REMOVE_POST = 'REMOVE_POST'
export const REMOVE_POST_DONE = 'REMOVE_POST_DONE'
export const REMOVE_POST_ERROR = 'REMOVE_POST_ERROR'

export const FETCH_POSTS_ALL = 'FETCH_POSTS_ALL'
export const FETCH_POSTS_ALL_DONE = 'FETCH_POSTS_ALL_DONE'
export const FETCH_POSTS_ALL_ERROR = 'FETCH_POSTS_ALL_ERROR'

export const CLEAR_POSTS = 'CLEAR_POSTS'

export const TOGGLE_EDIT_POST = 'TOGGLE_EDIT_POST'
