export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const REFRESHING_TOKEN = 'REFRESHING_TOKEN'
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_DONE = 'UPDATE_USER_DONE'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'
